name: second testing workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install deps
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test